DataObject:
  extensions:
    - DeprecatedDataObjectMethodsExtension
Object:
  extensions:
    - DeprecatedObjectMethodsExtension
LeftAndMain:
  extensions:
    - DeprecatedLeftAndMainMethodsExtension
ModelAdmin:
  extensions:
    - DeprecatedModelAdminMethodsExtension
SecurityAdmin:
  extensions:
    - DeprecatedSecurityAdminMethodsExtension
RestfulService:
  extensions:
    - DeprecatedRestfulServiceMethodsExtension
ContentNegotiator:
  extensions:
    - DeprecatedContentNegotiatorMethodsExtension
YamlFixture:
  extensions:
    - DeprecatedYamlfixtureMethodsExtension
Email:
  extensions:
    - DeprecatedEmailMethodsExtension
Mailer:
  extensions:
    - DeprecatedMailerMethodsExtension
GDBackend:
  extensions:
    - DeprecatedGDBackendMethodsExtension
ImagickBackend:
  extensions:
    - DeprecatedImagickBackendMethodsExtension
ModelAsController:
  extensions:
    - DeprecatedModelAsControllerMethodsExtension
RootURLController:
  extensions:
    - DeprecatedRootURLControllerMethodsExtension
SiteTree:
  extensions:
    - DeprecatedSiteTreeMethodsExtension
ErrorPage:
  extensions:
    - DeprecatedErrorPageMethodsExtension